version: '3.8'

services:

  mysql_db:
    image: mysql:latest
    restart: always
    networks:
      - app-tier
    volumes:
    - ./mysql/db:/var/lib/mysql
    ports:
        - "3306:3306"
    cap_add:
        - SYS_NICE
    environment:
        - MYSQL_DATABASE=app
        - MYSQL_USER=user
        - MYSQL_PASSWORD=1234
        - MYSQL_ROOT_PASSWORD=1234

  django_app:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    ports:
      - "8000:8000"
    links:
      - mysql_db:mysql_db
    depends_on:
      - mysql_db
    networks:
      - app-tier
    restart: always
    volumes:
      - ./django/app:/app

networks:
  app-tier:
    driver: bridge